= dotfiles
Dardan Bujupaj, 16.10.2018

== TODO

* [ ] install-script
* [ ] links to used tools

== Installation
=== Symlinks
To install a dotfile create a symlink at its expected location to the actual file in the repository.

 ln -s ~/.dotfiles/.zshrc ~/.zshrc

INFO: Some dotfiles require a bash command to be executed.
To execute the current line in vim use

 :.w ! bash

== Notes
=== .zshrc
==== nvm
nvm is loaded by .zshrc.
If the .nvm folder does not exist in the $HOME directory, nvm will not be loaded.
Install nvm with:

 curl -o- "https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh" | sh

Check https://github.com/creationix/nvm for the latest version.


=== vim
==== .vimrc
vim plugins are installed via Vundle. To use the .vimrc-dotfile, install Vundle like this:

 git clone https://github.com/VundleVim/Vundle.vim.git ~/.vim/bundle/Vundle.vim

==== asciidoc.vim
Filetype definitions for asciidoctor. Helps with filenames for `gf`.

 ln -s ~/.dotfiles/asciidoc.vim ~/.vim/ftplugin

=== sway
Install sway config to 

 ~/.config/sway/config

=== .Xdefaults
The colors in .Xdefaults are configured using c defines in .Xdefaults.raw
To preprocess the defines use

 cpp -E .Xdefaults.raw -o .Xdefaults
